package com.sahitol.collector.domain.safety

import android.content.Context
import com.sahitol.collector.domain.model.MaterialCategory
import org.json.JSONArray
import java.io.InputStreamReader

/**
 * Contextual Safety Content Manager (R-SAFE-01, T035, T039).
 * Supplies all 9 material-specific safety cards with full trilingual text (en, hi, mr),
 * audio keys for dynamic narration, hazard levels, prohibitions, and safe steps.
 */
object SafetyContentManager {

    private val BUILTIN_CARDS: List<SafetyCard> = listOf(
        SafetyCard(
            id = "SC-CAB-01",
            guideId = "SG-CABLE-01",
            materialIds = listOf("MAT-CAB-01", "MAT-CAB-02"),
            category = MaterialCategory.COPPER_CABLE,
            hazardLevel = HazardLevel.HIGH,
            hazardType = "TOXIC_FUMES",
            references = listOf("CPCB E-Waste (Management) Rules 2022 - Schedule II", "WHO Guidance on Health Risks from E-Waste Exposure (2021)"),
            audioKey = "sc_cab_01",
            locales = mapOf("en" to SafetyCardLocale("Do Not Burn Cable Insulation", "Toxic fume inhalation & severe respiratory damage", "Burning plastic or PVC insulation releases toxic dioxins, furans, and hydrochloric acid fumes that cause severe lung damage, bronchitis, and soil contamination.", "Keep cables completely intact in dry coils. Use handheld mechanical wire strippers or deliver intact coils to authorized recyclers equipped with mechanical cable granulators.", "Never burn cables in open ground fires, barrels, or enclosed drums.", "Warning: Do not burn cables. Burning plastic insulation releases toxic fumes that damage your lungs and the environment. Keep cables intact and use mechanical strippers or hand over to registered recyclers."), "hi" to SafetyCardLocale("तार का इंसुलेशन कभी न जलाएं", "जहरीला धुआं और फेफड़ों को भारी नुकसान", "प्लास्टिक या पीवीसी इंसुलेशन जलाने से खतरनाक डायऑक्सिन और तेजाबी धुआं निकलता है, जिससे फेफड़े खराब होते हैं और आसपास की जमीन दूषित होती है।", "तार को बिना जलाए सुरक्षित रखें। तार छीलने वाले सुरक्षित औजार (वायर स्ट्रिपर) का उपयोग करें या अधिकृत रीसाइक्लर को सौंपें।", "तार को कभी भी खुली आग, गड्ढे या ड्रम में न जलाएं।", "सावधानी: तार को कभी न जलाएं। प्लास्टिक जलने से जहरीला धुआं निकलता है जो फेफड़ों को नुकसान पहुंचाता है। तारों को बिना जलाए रखें और अधिकृत रीसाइक्लर को दें।"), "mr" to SafetyCardLocale("तारांचे इन्सुलेशन कधीही जाळू नका", "विषारी धूर आणि श्वसनविकारांचा गंभीर धोका", "प्लास्टिक इन्सुलेशन जाळल्याने अत्यंत विषारी डायऑक्सिन आणि ॲसिडयुक्त धूर निघतो, ज्यामुळे फुप्फुसांना गंभीर इजा होते आणि हवा प्रदूषित होते.", "तारा जशा आहेत तशा अखंड ठेवा. यांत्रिक वायर स्ट्रिपर वापरा किंवा केबल ग्रॅन्युलेटर असणाऱ्या अधिकृत रिसायकलिंग केंद्रात जमा करा.", "उघड्या आगीत, खड्ड्यात किंवा ड्रममध्ये तारा कधीही जाळू नका.", "सावधान: तारा कधीही जाळू नका. प्लास्टिक जाळल्याने विषारी धूर निघतो ज्यामुळे फुप्फुसांना इजा होते. तारा अखंड ठेवा आणि अधिकृत रिसायकलर्सना द्या.")),
            prohibitions = listOf(SafetyProhibition("no_dismantling", "No Dismantling", "बिना औजार न खोलें", "हातने तोडू नका", "drive_file_stream"), SafetyProhibition("no_burning", "No Burning", "आग न लगाएं", "कधीही जाळू नका", "local_fire_department"), SafetyProhibition("no_acid_bath", "No Acid Bath", "तेजाब का प्रयोग न करें", "ॲसिड वापरू नका", "science")),
            steps = listOf(SafetyStep(1, "Intact Storage Only", "तारों को सुरक्षित रखें", "अखंड तारा साठवा", "Keep coils intact in dry bags. Avoid exposure to rain or direct soil contact.", "तारों के बंडल को सूखे बोरे में रखें। बारिश और नमी से बचाएं।", "तारांचे बंडल कोरड्या जागी ठेवा. पाऊस आणि मातीपासून दूर ठेवा."), SafetyStep(2, "Mechanical Stripping Only", "वायर स्ट्रिपर का उपयोग करें", "यांत्रिक स्ट्रिपर वापरा", "Use handheld mechanical strippers only. Deliver large coils directly to authorized granulators.", "तार छीलने के लिए सिर्फ हस्तनिर्मित स्ट्रिपर का उपयोग करें। बड़े बंडल अधिकृत प्लांट में भेजें।", "फक्त हाताने चालणाऱ्या स्ट्रिपरचा वापर करा. मोठे बंडल अधिकृत प्लांटकडे पाठवा."), SafetyStep(3, "Direct Yard Handover", "अधिकृत यार्ड को सौंपें", "अधिकृत केंद्रात जमा करा", "Hand over intact to recyclers with certified pollution control equipment.", "प्रदूषण नियंत्रण बोर्ड से पंजीकृत रीसाइक्लर को ही तार बेचें।", "प्रदूषण नियंत्रण प्रमाणपत्र असणाऱ्या नोंदणीकृत रिसायकलरलाच द्या."))
        ),
        SafetyCard(
            id = "SC-PCB-01",
            guideId = "SG-PCB-01",
            materialIds = listOf("MAT-PCB-01", "MAT-PCB-02"),
            category = MaterialCategory.PCB,
            hazardLevel = HazardLevel.CRITICAL,
            hazardType = "CHEMICAL_BURNS_AND_LETHAL_GAS",
            references = listOf("CPCB Guidelines for Environmentally Sound Management of E-Waste (2022)", "Basel Convention Technical Guidelines on E-Waste (TGs 2021)"),
            audioKey = "sc_pcb_01",
            locales = mapOf("en" to SafetyCardLocale("No Acid Leaching or Open Heating of PCBs", "Lethal cyanide and nitric gas hazards", "Using nitric acid, aqua regia, or open gas burners on circuit boards produces lethal nitrogen oxides and hydrogen cyanide gas, causing permanent respiratory burns and death.", "Store printed circuit boards dry and unbroken in slotted crates. Hand over directly to formal e-waste recyclers registered with State Pollution Control Boards for automated metallurgical smelting.", "Never use acid tubs, gas blowtorches, or open charcoal hearths to extract precious metals.", "Warning: Never use acid or fire on circuit boards. Informal acid leaching releases lethal toxic gas and causes severe chemical burns. Store boards unbroken in dry crates and deliver to registered recyclers."), "hi" to SafetyCardLocale("सर्किट बोर्ड पर तेजाब या आग का प्रयोग न करें", "जानलेवा जहरीली गैस और तेजाब से जलने का खतरा", "सर्किट बोर्ड पर तेजाब (नाइट्रिक एसिड) डालने या आग पर तपाने से साइनाइड और नाइट्रोजन ऑक्साइड जैसी जहरीली गैसें निकलती हैं, जिससे फेफड़े जल सकते हैं और जान जा सकती है।", "बोर्ड को बिना तोड़े सूखी जगह पर क्रेट में रखें। केवल सीपीसीबी (CPCB) या राज्य प्रदूषण नियंत्रण बोर्ड से अधिकृत ई-कचरा रीसाइक्लर को ही सौंपें।", "सोना-चांदी निकालने के लिए कभी भी एसिड बाथ, बर्नर या कोयले की भट्टी का उपयोग न करें।", "सावधानी: सर्किट बोर्ड पर तेजाब या खुली आग कभी न लगाएं। अनौपचारिक एसिड से जानलेवा गैस निकलती है। बोर्ड को बिना तोड़े रखें और अधिकृत रीसाइक्लर को दें।"), "mr" to SafetyCardLocale("सर्किट बोर्डवर ॲसिड किंवा आगीचा वापर करू नका", "घातक विषारी वायू आणि गंभीर भाजण्याचा धोका", "सर्किट बोर्डवर ॲसिड टाकल्याने किंवा आगीवर गरम केल्याने सायनाइड आणि नायट्रोजन ऑक्साईडसारखे विषारी वायू तयार होतात, ज्यामुळे श्वसनसंस्था निकामी होऊन मृत्यू ओढवू शकतो.", "बोर्ड न तोडता कोरड्या जागी क्रेटमध्ये सुरक्षित ठेवा. केवळ अधिकृत ई-कचरा रिसायकलर्सनाच हे साहित्य सुरक्षित प्रक्रियेसाठी द्या.", "मौल्यवान धातू काढण्यासाठी ॲसिडची भांडी, गॅस बर्नर किंवा कोळशाच्या भट्ट्यांचा वापर कधीही करू नका.", "सावधान: सर्किट बोर्डवर ॲसिड किंवा आग वापरू नका. यातून घातक विषारी वायू बाहेर पडतो. बोर्ड कोरड्या क्रेटमध्ये सुरक्षित ठेवा आणि अधिकृत केंद्रात जमा करा.")),
            prohibitions = listOf(SafetyProhibition("no_acid_leaching", "No Acid Leaching", "तेजाब में न धोएं", "ॲसिड लीचिंग करू नका", "science"), SafetyProhibition("no_open_heating", "No Open Heating", "गैस पर न तपाएं", "उघड्या आगीवर तापवू नका", "local_fire_department"), SafetyProhibition("no_cyanide_bath", "No Cyanide Bath", "जहरीला रसायन न लगाएं", "सायनाइड वापरू नका", "dangerous")),
            steps = listOf(SafetyStep(1, "Keep Boards Intact", "सर्किट बोर्ड को अखंड रखें", "बोर्ड अखंड ठेवा", "Do not scrape, heat, or mechanically crush components off the board.", "बोर्ड पर लगे पुर्जों को जबरदस्ती न उखाड़ें और न ही गर्म करें।", "बोर्डवरील सुटे भाग तापवून किंवा तोडून काढू नका."), SafetyStep(2, "Dry Segregated Storage", "सूखी जगह पर अलग रखें", "कोरड्या जागी वेगळे ठेवा", "Store motherboards and green boards in anti-static or dry plastic crates.", "मदरबोर्ड को पानी और नमी से बचाकर प्लास्टिक क्रेट में अलग रखें।", "मदरबोर्ड प्लास्टिकच्या क्रेटमध्ये कोरड्या जागी सुरक्षित ठेवा."), SafetyStep(3, "Smelter / Refiner Route", "पंजीकृत स्मेल्टर को भेजें", "नोंदणीकृत स्मेल्टरला द्या", "Direct lot handover to authorized smelters with acid fume scrubbers.", "तेजाब नियंत्रण संयंत्र वाले अधिकृत रिफाइनर को ही बोर्ड सौंपें।", "फ्युम स्क्रबर यंत्रणा असणाऱ्या अधिकृत रिफायनरकडेच हस्तांतरित करा."))
        ),
        SafetyCard(
            id = "SC-CRT-01",
            guideId = "SG-CRT-01",
            materialIds = listOf("MAT-CRT-01"),
            category = MaterialCategory.CRT_MONITOR,
            hazardLevel = HazardLevel.CRITICAL,
            hazardType = "IMPLOSION_AND_LEAD_POISONING",
            references = listOf("CPCB Environmentally Sound Management of Cathode Ray Tubes (CRTs)", "E-Waste (Management) Rules 2022 - Treatment Standards"),
            audioKey = "sc_crt_01",
            locales = mapOf("en" to SafetyCardLocale("Do Not Break or Dismantle CRT Glass", "Violent vacuum implosion & toxic lead glass hazard", "Cathode Ray Tubes operate under high vacuum and contain up to 1.5kg of toxic lead plus hazardous cadmium/phosphor powder. Breaking the glass results in violent implosion and airborne toxic heavy metal dust.", "Keep CRT units fully assembled in their original plastic or wooden chassis. Transport face-down with padded screen support. Never separate the glass funnel from the faceplate.", "Never strike CRT tubes with hammers, snap the rear electron gun neck, or shatter the funnel.", "Warning: Do not break CRT monitor glass. CRTs are under vacuum and contain toxic lead and phosphor dust. Breaking causes violent implosion and severe cuts. Keep CRT displays intact and deliver face-down."), "hi" to SafetyCardLocale("सीआरटी (CRT) टीवी या मॉनिटर का कांच कभी न तोड़ें", "जोरदार धमाका (इम्प्लोजन) और लेड जहर का खतरा", "सीआरटी ट्यूब में तेज वैक्यूम और लगभग 1.5 किलो जहरीला लेड (सीसा) होता है। इसे तोड़ने पर यह जोरदार धमाके के साथ फूटता है और जहरीला लेड व फॉस्फोर पाउडर हवा में फैलता है।", "सीआरटी मॉनिटर को बिना तोड़े पूरा रखें। स्क्रीन को गद्देदार सतह पर नीचे की ओर रखकर सुरक्षित ले जाएं। ग्लास को कभी अलग न करें।", "ट्यूब को कभी हथौड़े से न फोड़ें और न ही पीछे की नली (नेक) को तोड़ें।", "सावधानी: सीआरटी मॉनिटर या टीवी का कांच कभी न फोड़ें। इसमें भारी वैक्यूम और जहरीला लेड होता है। फूटने पर यह विस्फोटक रूप लेता है। इसे पूरा सुरक्षित रखें।"), "mr" to SafetyCardLocale("सीआरटी (CRT) टीव्ही किंवा काच कधीही फोडू नका", "स्फोटक आकुंचन (इम्प्लोजन) आणि शिशाच्या विषाचा धोका", "सीआरटी ट्यूबमध्ये प्रचंड व्हॅक्यूम आणि दीड किलोपर्यंत विषारी शिसे असते. काच फुटल्यास जोरदार स्फोट होऊन विषारी पावडर हवेत पसरते आणि डोळ्यांना-शरीराला गंभीर जखमा होतात.", "सीआरटी संच न तोडता जसा आहे तसा ठेवा. स्क्रीनचा भाग खाली मऊ गादीवर ठेवून सुरक्षित वाहतूक करा. काच वेगळी करण्याचा प्रयत्न करू नका.", "ट्यूबवर हातोडा मारू नका किंवा मागचा बारीक भाग (नेक) तोडू नका.", "सावधान: सीआरटी टीव्ही किंवा कॉम्प्युटरची काच कधीही फोडू नका. यात तीव्र व्हॅक्यूम आणि विषारी शिसे असते. फुटल्यास मोठा धोका होतो. काच अखंड ठेवून अधिकृत ठिकाणी द्या.")),
            prohibitions = listOf(SafetyProhibition("no_dismantling", "No Dismantling", "हथौड़े से न तोड़ें", "फोडू नका", "drive_file_stream"), SafetyProhibition("no_burning", "No Burning", "आग में न डालें", "जाळू नका", "local_fire_department"), SafetyProhibition("no_acid_bath", "No Acid Bath", "तेजाब में न डालें", "ॲसिडमध्ये टाकू नका", "science")),
            steps = listOf(SafetyStep(1, "Intact Storage Only", "बिना तोड़े सीधा रखें", "अखंड उभे ठेवा", "Keep whole unit upright on wooden pallet. Do not stack more than 2 high.", "CRT मॉनिटर को लकड़ी के तख्ते पर सीधा रखें। 2 से ज्यादा एक के ऊपर एक न रखें।", "CRT मॉनिटर लाकडी फळीवर उभा ठेवा. एकावर एक 2 पेक्षा जास्त रचू नका."), SafetyStep(2, "Personal Protective Equipment", "दस्ताने और मास्क पहनें", "हातमोजे व मास्क वापरा", "Wear nitrile gloves and N95 dust mask if handling cracked or damaged housing units.", "टूटे हुए फ्रेम को छूते समय मोटे दस्ताने और N95 मास्क पहनें।", "तडा गेलेले मॉनिटर हाताळताना रबरी हातमोजे आणि N95 मास्क नक्की वापरा."), SafetyStep(3, "Direct Yard Handover", "सीधे रीसाइक्लर को सौंपें", "थेट केंद्रात पाठवा", "Transfer directly to certified dismantling facility without secondary crushing.", "बिना किसी तोड़-फोड़ के अधिकृत CRT डिस्मेंटलर को सौंपें।", "दुय्यम क्रशिंग न करता अधिकृत डिस्मेंटलिंग प्लांटकडे सुपूर्द करा."))
        ),
        SafetyCard(
            id = "SC-BAT-01",
            guideId = "SG-BATTERY-01",
            materialIds = listOf("MAT-BAT-01"),
            category = MaterialCategory.BATTERY_LI_ION,
            hazardLevel = HazardLevel.CRITICAL,
            hazardType = "CORROSIVE_ACID_AND_TOXIC_LEAD",
            references = listOf("CPCB Battery Waste Management Rules 2022", "MoEFCC Lead-Acid Battery Recycling Standards"),
            audioKey = "sc_bat_01",
            locales = mapOf("en" to SafetyCardLocale("Lead-Acid Battery Handling & Upright Storage", "Corrosive sulfuric acid & heavy metal toxic lead", "Contains concentrated sulfuric acid that causes permanent blindness and skin destruction on contact. Heavy metal lead accumulates in human bones and organs, causing neurological disability.", "Store upright in dedicated heavy-duty polyethylene leak-proof spill trays. Wrap both terminal posts with insulating electrical tape to prevent arcing and fire.", "Never tip on its side, pour liquid acid into gutters or open ground, or pry open sealed vent caps.", "Warning: Handle lead-acid batteries with care. They contain concentrated acid and toxic lead. Always keep them upright in a spill-proof tray, tape both terminals, and never drain acid into the ground."), "hi" to SafetyCardLocale("लेड-एसिड बैटरी: सीधा रखें और एसिड से बचें", "तेजाब का रिसाव और लेड (सीसा) जहर का खतरा", "इसमें गाढ़ा सल्फ्यूरिक तेजाब होता है जो त्वचा को तुरंत जला सकता है और आंखों की रोशनी छीन सकता है। सीसा शरीर में जाकर हड्डियों और दिमाग को नुकसान पहुंचाता है।", "बैटरी को हमेशा सीधा (अपराइट) प्लास्टिक ट्रे में रखें। दोनों खूंटियों (टर्मिनलों) पर इंसुलेशन टेप चिपकाएं ताकि स्पार्क न हो।", "बैटरी को कभी तिरछा न रखें, तेजाब को नाली या मिट्टी में न बहाएं, और ढक्कन जबरन न खोलें।", "सावधानी: बड़ी लेड-एसिड बैटरी को हमेशा सीधा रखें। इसमें गाढ़ा तेजाब होता है। दोनों टर्मिनलों पर टेप लगाएं और तेजाब को कभी भी जमीन पर न बहाएं।"), "mr" to SafetyCardLocale("लेड-ॲसिड बॅटरी: नेहमी सरळ ठेवा आणि ॲसिड टाळा", "तीव्र ॲसिड आणि विषारी शिशाचा गंभीर धोका", "यामध्ये तीव्र सल्फ्यूरिक ॲसिड असते ज्यामुळे त्वचा जळू शकते आणि डोळे निकामी होऊ शकतात. शिसे शरीरासाठी अत्यंत विषारी आहे.", "बॅटरी नेहमी सरळ (उभी) ठेवा जेणेकरून ॲसिड सांडणार नाही. स्पार्क टाळण्यासाठी दोन्ही टर्मिनल्सवर इन्सुलेशन टेप लावा.", "बॅटरी कधीही आडवी करू नका, ॲसिड नाल्यात किंवा जमिनीत टाकू नका आणि झाकण उघडण्याचा प्रयत्न करू नका.", "सावधान: लेड-ॲसिड बॅटरी नेहमी सरळ ठेवा. यात तीव्र ॲसिड असते. दोन्ही टोकांवर इन्सुलेशन टेप लावा आणि ॲसिड कधीही जमिनीवर सांडू देऊ नका.")),
            prohibitions = listOf(SafetyProhibition("do_not_invert", "Do Not Invert", "उलटा न रखें", "उलटी ठेवू नका", "swap_vert"), SafetyProhibition("no_acid_drainage", "No Acid Drainage", "तेजाब नाली में न बहाएं", "ॲसिड वाहू देऊ नका", "science"), SafetyProhibition("no_cracking_cases", "No Cracking Cases", "केसिंग न तोड़ें", "कव्हर फोडू नका", "build")),
            steps = listOf(SafetyStep(1, "Upright Position Only", "बैटरी को सीधा रखें", "बॅटरी नेहमी सरळ ठेवा", "Always store and transport in strictly upright orientation with terminal caps on.", "बैटरी को हमेशा सीधा रखें ताकि तेजाब बाहर न गिरे। कैप बंद रखें।", "बॅटरी नेहमी सरळ ठेवा जेणेकरून ॲसिड सांडणार नाही. टर्मिनल कॅप लावा."), SafetyStep(2, "Acid Neutralization Ready", "चूना या बेकिंग सोडा पास रखें", "चुना किंवा सोडा जवळ ठेवा", "Keep dry baking soda or lime nearby to neutralize accidental acid drips.", "अचानक तेजाब रिसने पर बेकिंग सोडा या चूना डालकर तुरंत शांत करें।", "ॲसिड गळती झाल्यास त्यावर खाण्याचा सोडा किंवा चुना टाका."), SafetyStep(3, "Authorized Lead Smelter", "अधिकृत लेड स्मेल्टर को दें", "नोंदणीकृत स्मेल्टरला द्या", "Sell only to CPCB/MPCB registered battery collection and secondary lead smelters.", "पंजीकृत बैटरी रिसाइकलर को ही बेचें। अवैध भट्ठियों में न बेचें।", "प्रदूषण मंडळाने प्रमाणित केलेल्या लेड रिसायकलर्सनाच विक्री करा."))
        ),
        SafetyCard(
            id = "SC-BAT-02",
            guideId = "SG-BATTERY-02",
            materialIds = listOf("MAT-BAT-02"),
            category = MaterialCategory.BATTERY_LI_ION,
            hazardLevel = HazardLevel.CRITICAL,
            hazardType = "THERMAL_RUNAWAY_AND_EXPLOSION",
            references = listOf("CPCB Battery Waste Management Rules 2022 - Electric Vehicle & Portable Batteries", "NFPA 855 Standard for the Installation of Stationary Energy Storage Systems"),
            audioKey = "sc_bat_02",
            locales = mapOf("en" to SafetyCardLocale("Lithium-Ion Battery Fire & Terminal Taping", "Thermal runaway fire reaching 800°C and toxic gas", "Damaged, compressed, or shorted lithium-ion cells enter self-sustaining thermal runaway, generating explosive 800°C fires that cannot be extinguished with water, emitting hydrofluoric acid gas.", "Inspect carefully for swelling, dents, or tears. Individually tape all exposed metal contact pads with non-conductive tape. Store separated in dry, vermiculite-lined or non-combustible containers.", "Never puncture with metal tools, throw into mixed metal scrap, expose to water, or crush underfoot.", "Warning: Lithium-ion batteries can catch fire and explode if damaged or shorted. Always tape all battery terminals individually with electrical tape. Never crush, puncture, or store loose in scrap bags."), "hi" to SafetyCardLocale("लिथियम-आयन बैटरी: आग और फटने का खतरा", "अचानक आग और 800 डिग्री तक तापमान का खतरा", "दबने, कटने या शॉर्ट सर्किट होने पर लिथियम बैटरी भीषण आग पकड़ सकती है। यह आग 800 डिग्री तक पहुंचती है और पानी से नहीं बुझती, साथ ही जहरीली गैस छोड़ती है।", "बैटरी पर सूजन या कट की जांच करें। दोनों टर्मिनलों पर अलग-अलग बिजली की टेप चिपकाएं। इसे सूखे प्लास्टिक के डिब्बे में अलग रखें।", "बैटरी को कभी दबाएं नहीं, धातु के औजार से न काटें, और न ही सामान्य कबाड़ की बोरी में ढीला छोड़ें।", "सावधानी: लिथियम बैटरी में आग और धमाके का भारी खतरा होता है। बैटरी के दोनों सिरों पर तुरंत टेप लगाएं। इसे कभी भी लोहे के औजार से न दबाएं और अलग रखें।"), "mr" to SafetyCardLocale("लिथियम-आयन बॅटरी: आग आणि स्फोटाचा इशारा", "अचानक 800 अंश सेल्सिअसची आग आणि विषारी वायू", "लिथियम बॅटरी दबल्यास, पंक्चर झाल्यास किंवा शॉर्ट झाल्यास अचानक प्रचंड भडका उडतो. ही आग पाण्याने विझत नाही आणि यातून अत्यंत विषारी वायू निघतो.", "बॅटरी फुगली आहे का ते तपासा. बॅटरीच्या प्रत्येक टोकावर स्वतंत्र इन्सुलेशन टेप लावा. कोरड्या, आगप्रतिबंधक डब्यात स्वतंत्र ठेवा.", "बॅटरीवर धारदार वस्तू मारू नका, हातोड्याने दाबू नका आणि इतर भंगारात मोकळी सोडू नका.", "सावधान: लिथियम बॅटरीला धक्का लागल्यास किंवा ती शॉर्ट झाल्यास मोठा भडका उडू शकतो. बॅटरीच्या टोकांना लगेच टेप लावा आणि ती इतर भंगारापासून वेगळी ठेवा.")),
            prohibitions = listOf(SafetyProhibition("do_not_puncture", "Do Not Puncture", "छेद न करें", "छिद्र पाडू नका", "drive_file_stream"), SafetyProhibition("no_water_submersion", "No Water Submersion", "पानी में न डालें", "पाण्यात टाकू नका", "water_drop"), SafetyProhibition("no_open_fire", "No Open Fire", "आग के पास न रखें", "उष्णतेजवळ ठेवू नका", "local_fire_department")),
            steps = listOf(SafetyStep(1, "Tape All Terminals", "टर्मिनल पर टेप लगाएं", "टर्मिनल्सवर टेप लावा", "Cover positive and negative metal terminals with non-conductive electrical tape.", "बैटरी के दोनों सिरों पर इंसुलेशन टेप लगाएं ताकि शॉर्ट सर्किट न हो।", "बॅटरीच्या दोन्ही बाजूंना विजेची टेप लावा जेणेकरून शॉर्ट सर्किट होणार नाही."), SafetyStep(2, "Fire Isolation Storage", "रेत या मिट्टी की बाल्टी रखें", "वाळूची बादली जवळ ठेवा", "Store away from direct sunlight in a dry bucket with sand nearby.", "बैटरी को धूप और गर्मी से दूर रखें। पास में सूखी रेत की बाल्टी रखें।", "उष्णतेपासून दूर ठेवा आणि जवळ सुक्या वाळूची बादली तयार ठेवा."), SafetyStep(3, "Specialized Li-Ion Route", "लिथियम रिसाइक्लर को दें", "लिथियम रिसायकलरला द्या", "Do not mix with lead-acid or general scrap; send to dedicated lithium processors.", "इसे सामान्य कबाड़ में न मिलाएं, विशेष लिथियम रिसाइकलर को सौंपें।", "सामान्य भंगारात मिसळू नका, विशेष लिथियम रिसायकलिंग प्लांटमध्ये पाठवा."))
        ),
        SafetyCard(
            id = "SC-BAT-03",
            guideId = "SG-BATTERY-03",
            materialIds = listOf("MAT-BAT-03", "MAT-BAT-04"),
            category = MaterialCategory.BATTERY_LI_ION,
            hazardLevel = HazardLevel.HIGH,
            hazardType = "UNKNOWN_CHEMISTRY_SHORT_CIRCUIT",
            references = listOf("CPCB Battery Waste Management Rules 2022 - Collection & Sorting", "UN Recommendations on the Transport of Dangerous Goods (Model Regs)"),
            audioKey = "sc_bat_03",
            locales = mapOf("en" to SafetyCardLocale("Unknown & Mixed Battery Segregation", "Multi-chemistry cross-contact and fire risk", "Unlabelled or custom batteries may contain reactive lithium, toxic nickel-cadmium, or mercury. Loose mixing allows terminals to touch, generating spark ignition and container fires.", "Place loose batteries in a non-conductive plastic container. Ensure individual terminals cannot contact neighboring metal surfaces. Route to an authorized battery collection facility.", "Never cut outer shrink wrap to identify chemistry, drop into metal drums, or transport in loose bulk sacks.", "Warning: Segregate unknown batteries. Mixing different battery types can cause short circuits and fires. Place in a non-conductive plastic box and never peel the outer casing to identify them."), "hi" to SafetyCardLocale("अज्ञात बैटरी: अलग डिब्बे में सुरक्षित रखें", "आपस में टकराने से चिंगारी और आग का खतरा", "बिना नाम वाली बैटरी में लिथियम, कैडमियम या पारा हो सकता है। इन्हें आपस में मिलाकर रखने पर शॉर्ट सर्किट से कबाड़ के थैले में आग लग सकती है।", "बैटरियों को अलग प्लास्टिक के डिब्बे में रखें ताकि उनके सिरे आपस में न टकराएं। अधिकृत बैटरी संकलन केंद्र को ही दें।", "पहचान करने के लिए बैटरी का बाहरी प्लास्टिक कभी न काटें और न ही लोहे के ड्रम में फेंकें।", "सावधानी: अज्ञात बैटरियों को हमेशा अलग प्लास्टिक के डिब्बे में रखें। अलग-अलग बैटरियां छूने से चिंगारी और आग भड़क सकती है। इनका छिलका कभी न उतारें।"), "mr" to SafetyCardLocale("अज्ञात बॅटरी: स्वतंत्र प्लास्टिक डब्यात ठेवा", "एकमेकांना स्पर्श झाल्यास ठिणगी आणि आगीचा धोका", "लेबल नसलेल्या बॅटऱ्यांमध्ये लिथियम किंवा कॅडमियम असू शकते. त्या एकत्र ठेवल्यास टोकांचा एकमेकांना स्पर्श होऊन आगीचा मोठा धोका संभवतो.", "बॅटऱ्या स्वतंत्र प्लास्टिकच्या डब्यात सुरक्षित ठेवा जेणेकरून त्या एकमेकांना घासणार नाहीत. अधिकृत संकलन केंद्रात द्या.", "रसायन ओळखण्यासाठी बॅटरीचे बाहेरील आवरण कापू नका किंवा लोखंडी पिंपात टाकू नका.", "सावधान: माहिती नसलेल्या बॅटऱ्या स्वतंत्र प्लास्टिक डब्यात ठेवा. एकमेकांना स्पर्श झाल्यास आग लागू शकते. बॅटरीचे कव्हर काढण्याचा प्रयत्न करू नका.")),
            prohibitions = listOf(SafetyProhibition("no_mixed_piles", "No Mixed Piles", "सभी बैटरी एक साथ न रखें", "सर्व एकत्र ठेवू नका", "layers_clear"), SafetyProhibition("do_not_disassemble", "Do Not Disassemble", "पुर्जे अलग न करें", "भाग सुटे करू नका", "build"), SafetyProhibition("avoid_metal_contact", "Avoid Metal Contact", "लोहे के साथ न रखें", "धातूच्या संपर्कात आणू नका", "lock")),
            steps = listOf(SafetyStep(1, "Sort and Segregate", "बैटरी को प्रकार अनुसार छांटें", "प्रकारानुसार वेगळे करा", "Separate button cells, cylindrical cells, and mobile batteries into distinct plastic bins.", "बटन सेल, पेंसिल सेल और मोबाइल बैटरी को अलग-अलग प्लास्टिक डिब्बे में रखें।", "बटन सेल आणि मोबाईल बॅटऱ्या वेगवेगळ्या प्लास्टिक डब्यात ठेवा."), SafetyStep(2, "Keep Dry and Covered", "सूखे और ढके स्थान पर रखें", "कोरड्या व झाकलेल्या जागी ठेवा", "Protect from rain and conductive liquid moisture that could bridge terminals.", "पानी और नमी से बचाकर ढक्कन वाले डिब्बे में रखें।", "पावसाचे पाणी किंवा ओलावा लागू न देता झाकण असलेल्या डब्यात ठेवा."), SafetyStep(3, "Hand Over to Certified Depot", "अधिकृत डिपो को दें", "अधिकृत केंद्रात जमा करा", "Deliver segregated batteries to certified electronic waste collection depots.", "प्रमाणित ई-कचरा संग्रहण केंद्र को सौंपें।", "प्रमाणित ई-कचरा संकलन केंद्रात सुपूर्द करा."))
        ),
        SafetyCard(
            id = "SC-DAM-01",
            guideId = "SG-DAMAGED-01",
            materialIds = listOf("MAT-PCB-01", "MAT-PCB-02", "MAT-BAT-01", "MAT-BAT-02", "MAT-BAT-03", "MAT-BAT-04", "MAT-CRT-01", "MAT-LCD-01", "MAT-MOT-01", "MAT-MOT-02", "MAT-MIX-01", "MAT-MIX-02", "MAT-UNK-01"),
            category = MaterialCategory.OTHER,
            hazardLevel = HazardLevel.CRITICAL,
            hazardType = "ACTIVE_CHEMICAL_OR_THERMAL_EMERGENCY",
            references = listOf("CPCB Guidelines on Storage & Transportation of Hazardous E-Waste", "Disaster Management Division Ministry of Home Affairs Protocol"),
            audioKey = "sc_dam_01",
            locales = mapOf("en" to SafetyCardLocale("Damaged, Leaking, or Overheating Material", "Immediate stop handling & bystander clearance", "Hissing noises, pungent odors, swelling, chemical fluid leaks, or hot surfaces indicate an ongoing hazardous chemical event or imminent thermal reaction.", "Cease handling immediately. Clear all bystanders to a safe distance (minimum 10 meters) upwind. If safe to do so, place in an outdoor shaded sand container. Notify formal response or authorized disposal facility.", "Never touch leaking liquid with bare hands, inhale fumes, pour water on suspected battery reactions, or load onto passenger transport.", "Emergency Alert: If scrap is hissing, smoking, leaking fluid, or hot, stop handling immediately. Move bystanders away at least 10 meters upwind. Do not touch leaking chemicals. Seek authorized emergency help."), "hi" to SafetyCardLocale("क्षतिग्रस्त, रिसती या गर्म होती सामग्री: तुरंत रुकें", "सामान से तुरंत दूर हटें और दूसरों को बचाएं", "यदि कबाड़ से फुफकारने की आवाज आए, बदबू निकले, धुआं उठे, तरल पदार्थ रिसे या वह बहुत गर्म हो, तो यह भीषण रासायनिक खतरे या आग की शुरुआत है।", "तुरंत छूना बंद करें। सभी लोगों को कम से कम 10 मीटर दूर हटाएं। यदि सुरक्षित हो तो इसे खुले स्थान पर रेत में रखें और तुरंत अधिकृत केंद्र या आपातकालीन मदद से संपर्क करें।", "बहते केमिकल को नंगे हाथों से न छुएं, धुएं को सांस में न लें, और इसे कभी भी आम सवारी गाड़ी में न लादें।", "आपातकालीन चेतावनी: यदि कबाड़ से धुआं निकले, फुफकार की आवाज आए या केमिकल बहे, तो उसे तुरंत छोड़ दें। कम से कम 10 मीटर दूर हटें और दूसरों को भी हटाएं। केमिकल को न छुएं।"), "mr" to SafetyCardLocale("खराब, गळती होणारे किंवा गरम साहित्य: त्वरित थांबा", "हात लावणे तात्काळ थांबवा आणि लोकांना दूर करा", "सामान गरम होणे, वास येणे, धूर निघणे किंवा रासायनिक द्रव गळणे हे मोठ्या रासायनिक धोक्याचे किंवा आगीचे लक्षण आहे.", "साहित्य हाताळणे त्वरित थांबवा. सर्व लोकांना कमीतकमी १० मीटर अंतरावर सुरक्षित ठेवा. शक्य असल्यास उघड्या जागेत वाळूमध्ये ठेवा आणि अधिकृत मदत घ्या.", "गळणाऱ्या द्रवाला उघड्या हाताने स्पर्श करू नका, धूर श्वासात घेऊ नका आणि वाहनांमध्ये हे साहित्य भरू नका.", "धोका सूचना: जर साहित्यातून धूर निघत असेल, आवाज येत असेल किंवा केमिकल गळत असेल तर ताबडतोब लांब व्हा. लोकांना १० मीटर दूर ठेवा आणि रासायनिक द्रवाला हात लावू नका.")),
            prohibitions = listOf(SafetyProhibition("no_inhalation", "No Inhalation", "धुआं न सूंघें", "धूर श्वास घेऊ नका", "masks"), SafetyProhibition("do_not_touch_leaks", "Do Not Touch Leaks", "रिसाव को हाथ न लगाएं", "गळतीला हात लावू नका", "do_not_touch"), SafetyProhibition("do_not_mix", "Do Not Mix", "अन्य कबाड़ में न मिलाएं", "इतर भंगारात मिसळू नका", "layers_clear")),
            steps = listOf(SafetyStep(1, "Isolate in Open Air", "खुली हवा में अलग रखें", "उघड्या हवेत वेगळे ठेवा", "Move leaking, swelling, or smoking items outdoors away from flammable materials.", "धुआं निकल रही या सूजी हुई बैटरी को तुरंत खुले मैदान में अलग रख दें।", "धूर निघत असलेले किंवा फुगलेले साहित्य लगेच उघड्या जागेत हलवा."), SafetyStep(2, "Cover with Dry Sand", "सूखी रेत से ढकें", "सुक्या वाळूने झाका", "Never pour water on chemical fires; smother completely with dry sand or dirt.", "केमिकल या बैटरी की आग पर कभी पानी न डालें, केवल सूखी रेत डालें।", "केमिकलच्या आगीवर पाणी टाकू नका, त्यावर फक्त सुकी वाळू टाका."), SafetyStep(3, "Notify Hazardous Disposal", "विशेष निपटान टीम को बताएं", "विशेष पथकाला कळवा", "Contact authorized hazardous waste handler for controlled container pickup.", "खतरनाक अपशिष्ट निवारण टीम से संपर्क कर सुरक्षित उठवाएं।", "धोकादायक कचरा व्यवस्थापन केंद्राला कळवून सुरक्षित विल्हेवाट लावा."))
        ),
        SafetyCard(
            id = "SC-PLA-01",
            guideId = "SG-PLASTIC-01",
            materialIds = listOf("MAT-PLA-01", "MAT-PLA-02"),
            category = MaterialCategory.RIGID_PLASTIC,
            hazardLevel = HazardLevel.HIGH,
            hazardType = "BROMINATED_FLAME_RETARDANTS",
            references = listOf("Stockholm Convention on Persistent Organic Pollutants (POPs)", "CPCB Guidelines on Recycling of Plastics from E-Waste"),
            audioKey = "sc_pla_01",
            locales = mapOf("en" to SafetyCardLocale("Flame-Retardant Electronics Plastics: No Open Burning", "Carcinogenic polybrominated dioxin emissions", "E-waste plastics (ABS-FR, HIPS-FR) contain brominated flame retardant additives. Heating or open burning releases polybrominated dibenzodioxins, highly toxic persistent organic pollutants.", "Segregate rigid electronic casings from household bottles and food containers. Keep intact in clean sacks and route to authorized e-waste shredding facilities with density-separation equipment.", "Never burn plastics for volume reduction, melt in open pots, or re-extrude into consumer utensils or toys.", "Warning: Do not burn electronics plastics. Monitor and TV casings contain flame retardants that release cancer-causing toxic smoke when burned. Keep them separate from bottles and send to authorized recyclers."), "hi" to SafetyCardLocale("इलेक्ट्रॉनिक्स प्लास्टिक: कभी न जलाएं या पिघलाएं", "कैंसर पैदा करने वाले जहरीले धुएं से बचाव", "टीवी, कंप्यूटर और प्रिंटर के प्लास्टिक में आग रोकने वाले ब्रोमीन रसायन होते हैं। इसे जलाने या खुले बर्तन में पिघलाने पर जानलेवा कैंसरकारी धुआं निकलता है।", "इलेक्ट्रॉनिक प्लास्टिक को पानी की बोतलों व घरेलू प्लास्टिक से अलग रखें। इसे अधिकृत रीसाइक्लर को सौंपें जिनके पास सुरक्षित श्रेडर मशीनें हों।", "कबाड़ कम करने के लिए इसे कभी न जलाएं, न पिघलाएं और न ही घरेलू बर्तन बनाने में इस्तेमाल करें।", "सावधानी: इलेक्ट्रॉनिक्स के प्लास्टिक को कभी न जलाएं। कंप्यूटर और टीवी के प्लास्टिक में खतरनाक रसायन होते हैं। इन्हें साधारण प्लास्टिक से अलग रखें और अधिकृत रीसाइक्लर को दें।"), "mr" to SafetyCardLocale("इलेक्ट्रॉनिक्स प्लास्टिक: कधीही जाळू नका", "कर्करोगास कारणीभूत ठरणारा विषारी धूर टाळा", "टीव्ही, कॉम्प्युटरच्या प्लास्टिकमध्ये ब्रोमीनयुक्त रसायने असतात. हे जाळल्याने अत्यंत विषारी डायऑक्सिन धूर निघतो, ज्यामुळे कर्करोगाचा धोका निर्माण होतो.", "हे प्लास्टिक पाण्याच्या बाटल्या व घरगुती प्लास्टिकपासून वेगळे ठेवा. सुरक्षित प्रक्रिया करणाऱ्या अधिकृत ई-कचरा केंद्रातच जमा करा.", "जागेची बचत करण्यासाठी प्लास्टिक कधीही जाळू नका आणि उघड्या कढईत वितळवू नका.", "सावधान: इलेक्ट्रॉनिक्सचे प्लास्टिक कधीही जाळू नका. यात आगप्रतिबंधक विषारी रसायने असतात जी जाळल्यास कर्करोगाचा धोका होतो. हे प्लास्टिक वेगळे ठेवा आणि अधिकृत केंद्रात द्या.")),
            prohibitions = listOf(SafetyProhibition("no_open_flame", "No Open Flame", "खुली आग न लगाएं", "आग लावू नका", "local_fire_department"), SafetyProhibition("no_solvent_melting", "No Solvent Melting", "केमिकल में न पिघलाएं", "रसायनात विरघळवू नका", "science"), SafetyProhibition("no_kitchen_sorting", "No Kitchen Sorting", "घर में काम न करें", "घरात साठवू नका", "home")),
            steps = listOf(SafetyStep(1, "Intact Sorting", "प्लास्टिक को साबुत छांटें", "प्लास्टिक न तोडता वेगळे करा", "Keep monitor and TV plastic casings in large intact pieces without crushing.", "टीवी और मॉनिटर के प्लास्टिक कैबिनेट को बिना तोड़े अलग रखें।", "टीव्ही आणि मॉनिटरच्या प्लास्टिक कव्हरला न तोडता वेगळे ठेवा."), SafetyStep(2, "No Open Air Flame", "खुली आग में न जलाएं", "उघड्या आगीत जाळू नका", "Electronics plastics contain flame retardants that generate toxic smoke if heated.", "इस प्लास्टिक में विषैले केमिकल होते हैं, इसे जलाने से जानलेवा गैस निकलती है।", "या प्लास्टिकमध्ये विषारी घटक असतात, त्यामुळे ते जाळल्यास विषारी वायू तयार होतो."), SafetyStep(3, "Polymer Shredder Route", "अधिकृत श्रेडर प्लांट को दें", "अधिकृत श्रेडर प्लांटकडे पाठवा", "Deliver to registered recyclers equipped with air filtration and shredding systems.", "फिल्टर युक्त अधिकृत प्लास्टिक रिसाइक्लिंग प्लांट को ही भेजें।", "हवा शुद्धीकरण यंत्रणा असणाऱ्या अधिकृत प्लांटकडेच पाठवा."))
        ),
        SafetyCard(
            id = "SC-MIX-01",
            guideId = "SG-MIXED-01",
            materialIds = listOf("MAT-MIX-01", "MAT-MIX-02", "MAT-OTH-01", "MAT-UNK-01"),
            category = MaterialCategory.MIXED_EWASTE,
            hazardLevel = HazardLevel.HIGH,
            hazardType = "CONCEALED_HAZARDS_IN_ASSEMBLIES",
            references = listOf("CPCB E-Waste Rules 2022 - Collection & Channelization", "National Safety Council India - E-Waste Handling Practices"),
            audioKey = "sc_mix_01",
            locales = mapOf("en" to SafetyCardLocale("Mixed Electronic Assemblies: Do Not Force Dismantle", "Concealed capacitors, mercury switches & lithium cells", "Unsorted electronic equipment often conceals charged high-voltage capacitors, mercury tilt switches, or hidden pouch lithium batteries that explode upon physical impact.", "Keep mixed electronic devices completely sealed in sturdy cardboard boxes or heavy bags. Mark the lot as 'Review Required' and allow formal recyclers to conduct technical evaluation.", "Never use crowbars, axes, or heavy hammers to crack open sealed electronic housings for manual sorting.", "Warning: Do not force open mixed electronic devices. Sealed equipment may conceal high-voltage electrical charges or hidden batteries. Keep assemblies intact in sturdy containers for inspection."), "hi" to SafetyCardLocale("मिश्रित इलेक्ट्रॉनिक सामान: जबरन न तोड़ें", "छिपे हुए करंट, पारे और बैटरी का खतरा", "मिश्रित ई-कचरे के अंदर बिजली से चार्ज कैपेसिटर, पारे (मरकरी) के स्विच या छिपी हुई लिथियम बैटरी हो सकती है, जिन पर चोट लगने से करंट या धमाका हो सकता है।", "सामान को बिना तोड़े मजबूत बक्सों या बोरियों में रखें। इसे 'रिव्यू रिक्वायर्ड' मानकर अधिकृत रीसाइक्लर को तकनीकी जांच के लिए सौंपें।", "सामान को छांटने के लिए कभी भी हथौड़े, कुल्हाड़ी या सब्बल से जबरन न तोड़ें।", "सावधानी: पुराने इलेक्ट्रॉनिक उपकरणों को जबरन न तोड़ें। इनके अंदर करंट या छिपी हुई बैटरी हो सकती है जो चोट लगने पर फट सकती है। इन्हें बक्से में सुरक्षित रखें।"), "mr" to SafetyCardLocale("मिश्रित इलेक्ट्रॉनिक वस्तू: बळजबरीने फोडू नका", "विजेचा धक्का, पारा आणि छुपी बॅटरीचा धोका", "मिश्रित ई-कचऱ्यामध्ये चार्ज असलेले कॅपेसिटर, पाऱ्याचे स्विच किंवा छुपी लिथियम बॅटरी असू शकते. घाव घातल्यास मोठा शॉक किंवा स्फोट होऊ शकतो.", "वस्तू न तोडता मजबूत खोक्यात किंवा गोणीत ठेवा. अधिकृत केंद्रात तांत्रिक तपासणीसाठी जमा करा.", "भाग वेगळे करण्यासाठी हातोडा किंवा लोखंडी रॉडने उपकरणे फोडण्याचा प्रयत्न कधीही करू नका.", "सावधान: जुनी इलेक्ट्रॉनिक उपकरणे जबरदस्तीने फोडू नका. यात विजेचा धक्का किंवा बॅटरी फुटण्याचा धोका असू शकतो. सामान खोक्यात सुरक्षित ठेवा.")),
            prohibitions = listOf(SafetyProhibition("no_force_prying", "No Force Prying", "जबरदस्ती न खोलें", "जबरदस्तीने उघडू नका", "build"), SafetyProhibition("no_glass_smashing", "No Glass Smashing", "कांच न तोड़ें", "काच फोडू नका", "dangerous"), SafetyProhibition("no_burning_wires", "No Burning Wires", "तार न जलाएं", "तारा जाळू नका", "local_fire_department")),
            steps = listOf(SafetyStep(1, "Keep Assembled Intact", "सामग्री को साबुत रखें", "उपकरण अखंड ठेवा", "Store mixed electronic units intact without forcibly breaking open casings.", "पुराने इलेक्ट्रॉनिक्स उपकरण को बिना तोड़े साबुत अवस्था में रखें।", "इलेक्ट्रॉनिक उपकरण जबरदस्तीने न उघडता जसे आहे तसेच ठेवा."), SafetyStep(2, "Prevent Sharp Hazards", "धारदार कांच और तारों से बचें", "काच व तारांपासून सावध राहा", "Use heavy-duty leather or canvas gloves to prevent cuts from sharp edges.", "कांच और धारदार किनारों से बचने के लिए मोटे चमड़े के दस्ताने पहनें।", "तीक्ष्ण कडा आणि काचेपासून बचावासाठी जाड हातमोजे वापरा."), SafetyStep(3, "Direct Aggregator Handover", "पंजीकृत एग्रीगेटर को दें", "नोंदणीकृत केंद्रात द्या", "Deliver directly to authorized collection centers for mechanized disassembly.", "मशीन से खोलने वाले अधिकृत ई-कचरा केंद्र को ही सौंपें।", "यांत्रिक पद्धतीने सुटे भाग करणाऱ्या अधिकृत संकलन केंद्रात द्या."))
        ),
    )

    fun getAllCards(): List<SafetyCard> = BUILTIN_CARDS

    fun getCard(id: String): SafetyCard? = BUILTIN_CARDS.find { it.id.equals(id, ignoreCase = true) }

    fun getCardForCategory(category: MaterialCategory): SafetyCard? {
        return when (category) {
            MaterialCategory.COPPER_CABLE -> getCard("SC-CAB-01")
            MaterialCategory.PCB -> getCard("SC-PCB-01")
            MaterialCategory.CRT_MONITOR -> getCard("SC-CRT-01")
            MaterialCategory.BATTERY_LI_ION -> getCard("SC-BAT-02")
            MaterialCategory.ELECTRIC_MOTOR -> getCard("SC-MIX-01")
            MaterialCategory.MIXED_EWASTE -> getCard("SC-MIX-01")
            MaterialCategory.RIGID_PLASTIC -> getCard("SC-PLA-01")
            MaterialCategory.OTHER -> getCard("SC-DAM-01")
            else -> getCard("SC-MIX-01")
        }
    }

    fun getCardForMaterial(materialId: String): SafetyCard? {
        val normalized = materialId.uppercase()
        return BUILTIN_CARDS.find { card -> card.materialIds.any { it.equals(normalized, ignoreCase = true) } }
            ?: when {
                normalized.contains("CAB") -> getCard("SC-CAB-01")
                normalized.contains("PCB") -> getCard("SC-PCB-01")
                normalized.contains("CRT") -> getCard("SC-CRT-01")
                normalized.contains("BAT-01") -> getCard("SC-BAT-01")
                normalized.contains("BAT") -> getCard("SC-BAT-02")
                normalized.contains("PLA") -> getCard("SC-PLA-01")
                else -> getCard("SC-MIX-01")
            }
    }
}
