"""Documentation-baseline authoring helper. Run only to recreate the initial catalog.

Do not run after implementation starts: it resets planning state. The normal commands
are render_docs.py and check_docs.py. Standard library only, Python 3.10+.
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
P = ROOT / 'docs/planning'
if (P / 'status.json').exists():
    raise SystemExit('Baseline already exists. Edit catalog/status directly; use render_docs.py. Refusing to reset progress.')

# id | phase | title | prerequisites | reading | output / implementation contract
TASKS = '''
T001|0|Bootstrap repository and compatible toolchain||03_TECHSPEC,09_DECISIONS,11_SECRETS_CHECKLIST|Create Android/API/web project skeletons without inventing UI; pin a tested toolchain and dependency locks; add environment examples, PostGIS Compose service, CI lint/test/build jobs and documented commands.
T002|0|Obtain and register owner-generated Stitch designs||05_DESIGN_STITCH,04_APPFLOW|Present the prepared screen briefs by batch; owner generates screens; read the designated Stitch project through MCP; save screen IDs, revisions and approved state coverage in design/stitch/SCREEN_REGISTRY.md. Repeat this gate for later batches; the initial spike needs S00 only.
T003|0|Prove Android feasibility on a real phone|T001,T002|03_TECHSPEC,19_AI_ML,05_DESIGN_STITCH|Implement approved S00 diagnostic screen; capture/compress photo, save/read Room row after restart, run a bundled LiteRT baseline prediction in airplane mode, record phone/toolchain/APK evidence. Baseline prediction is not the trained SahiTol classifier. Failure is a visible blocker, never automatic PWA substitution.
T004|0|Complete secondary-research and source register||21_RESEARCH_EVIDENCE,22_REGULATORY_SAFETY,PROBLEM_STATEMENT|Build 5–7 attributed desk-research insight cards and 2–3 labelled personas; retain source/date/scope/limitations, link insights to requirement IDs; record primary fieldwork as not conducted and check the authenticated official brief/cutoff when available.
T005|1|Build reproducible data import and validation tools|T001|18_DATA_PROVENANCE,06_SCHEMA|Implement PDF/CSV/JSON import staging, pandas cleaning, field-level lineage, cached geocoding with provider policy, validation/quarantine, duplicate detection, reproducible seed and synthetic scripts. Invalid records must remain inspectable and never count as accepted.
T006|1|Implement PostgreSQL/PostGIS schema and migrations|T001|06_SCHEMA,16_API_CONTRACT,04_APPFLOW|Create tables, indexes, route/role constraints, integer money/weight, immutable events, versions and sync results. Test migration on empty DB and upgrade fixtures; verify extension and private DB permissions locally and hosted.
T007|1|Implement phone/PIN authentication and ownership|T006|16_API_CONTRACT,12_GUARDRAILS,11_SECRETS_CHECKLIST|Implement Argon2id PIN storage, rate-limited phone/PIN login, rotating/revocable session flow, COLLECTOR/RECYCLER/ADMIN authorization, device scoping, explicit isolated demo access, online first activation and secure Android session continuation contract.
T008|1|Implement private media storage adapter|T006,T007|06_SCHEMA,16_API_CONTRACT,DEPLOYMENT|Implement local-volume and Supabase-private-storage adapters; bounded image upload/validation/checksum, short-lived authorized access, missing-upload recovery and PDF storage. No permanent files on the free API host filesystem.
T009|1|Implement versioned reference bootstrap and delta APIs|T006,T007|16_API_CONTRACT,17_OFFLINE_SYNC|Expose material/alias/safety/price/directory snapshots with versions, policy parameters, source timestamps, tombstones, expiry and opaque cursor; filter by region and role; provide labelled bundled demo cache for first offline launch.
T010|1|Curate material taxonomy and language aliases|T004,T005,T006|18_DATA_PROVENANCE,22_REGULATORY_SAFETY,14_TRANSLATION_AUDIO_AUDIT|Seed every PS-named material, battery chemistry and UNKNOWN/OTHER; separate reference catalog from observed lot material; attach route, contextual safety, units, condition and hi/mr/en aliases. Add provenance-dependent routing for plastics/mixed waste.
T011|1|Create attributed price seed and observation pipeline|T004,T005,T006,T010|18_DATA_PROVENANCE,03_TECHSPEC|Import dated public buying/quoted/selling observations, unit/geography/condition/source metadata and licence/usage notes; partition demo series; add authenticated observation entry and review. Never fill missing live prices with synthetic rows.
T012|1|Build Delhi-NCR and Maharashtra facility directory|T004,T005,T006,T010|18_DATA_PROVENANCE,22_REGULATORY_SAFETY|Import small CPCB/DPCC/MPCB subsets; preserve facility role, registry/list date, route registration, validity, material acceptance evidence and field lineage; review geocodes, deduplicate facilities, and mark unknown pickup/rates as unknown.
T013|2|Implement Android Room repositories and durable outbox|T003,T006|17_OFFLINE_SYNC,06_SCHEMA|Implement local entities, migrations, atomic object+event+outbox write, staged image persistence, cache reads, user partition and logout preservation. Prove process death cannot show a saved record that was lost.
T014|2|Implement server synchronization protocol|T006,T007,T008,T009|17_OFFLINE_SYNC,16_API_CONTRACT|Implement push per-operation responses, dependency ordering, expected versions, payload fingerprints, atomic idempotency storage and pull deltas/tombstones. Prove crash-after-commit retry produces one domain effect.
T015|2|Implement Android background and manual synchronization|T013,T014|17_OFFLINE_SYNC,04_APPFLOW|Drain durable outbox through unique WorkManager jobs, network constraints/backoff and foreground/manual action; handle 401/409/422/429/5xx, partial media uploads and ACK loss; persist cursors only after local transaction commit.
T016|2|Implement lot and lifecycle backend|T006,T007,T008,T010,T014|06_SCHEMA,04_APPFLOW,16_API_CONTRACT|Create/update/list/cancel lot commands with owner checks, positive weight and validation, immutable estimates/suggestions, location quality, photos and transition events; prohibit direct arbitrary status PATCH.
T017|2|Implement approved collector onboarding and lot screens|T002,T007,T009,T013,T015,T016|05_DESIGN_STITCH,04_APPFLOW,14_TRANSLATION_AUDIO_AUDIT|Implement C01–C05,C14,C15 as approved Compose screens; use Room-only reads, photo permission/import fallback, manual material selection, condition/weight, resumable drafts, local save result, language/session/sync states. Model integration arrives in T034.
T018|3|Implement price statistics and snapshot valuation|T011,T016|03_TECHSPEC,06_SCHEMA,16_API_CONTRACT|Implement comparable observation filtering, weighted quantiles, confidence, history, sparse/stale/missing handling and per-lot immutable valuation snapshots. Publish shared fixtures for Python/Kotlin parity and preserve quote vs final amount semantics.
T019|3|Implement eligible recycler matching and map data|T012,T018|03_TECHSPEC,22_REGULATORY_SAFETY,16_API_CONTRACT|Implement hard route/material/status/service/weight filters, PostGIS distance, normalized scoring and explanation, missing-data rules, top candidates and no-match behavior; publish offline parity fixtures and cache policy.
T020|3|Implement approved collector price and recycler views|T002,T017,T018,T019|05_DESIGN_STITCH,04_APPFLOW|Implement C06–C09: board/trends, source details, observation entry, estimates, quote comparisons, directory/list/details and online map; cache age, no price/no match and permission-denied states; selection offline is intent only.
T021|3|Implement recycler profile and offer workflows|T007,T016,T019|16_API_CONTRACT,04_APPFLOW,06_SCHEMA|Implement facility-user linkage, self-declared operational profile, material/rate/pickup updates, incoming requests, offer/reject/expiry, collector acceptance with one active agreement, cancellation and immutable terms.
T022|3|Implement approved recycler console and phone layout|T002,T021|05_DESIGN_STITCH,04_APPFLOW,12_GUARDRAILS|Implement R01–R03,R06,R07 responsive React/Vite views for authorized facility users; incoming/lot evidence/offer/profile/history/export interactions; work on borrowed second Android phone without a separate recycler APK.
T023|4|Implement handover proposals and confirmations|T014,T021|04_APPFLOW,16_API_CONTRACT,17_OFFLINE_SYNC|Implement pending proposal, canonical payload/hash/event chain, authenticated recycler confirmation, collector acknowledgement of changes, duplicate-safe outcome, disputes and immutable revision links; create minimal public verification response.
T024|4|Implement approved offline QR and collector receipt|T002,T017,T023|05_DESIGN_STITCH,17_OFFLINE_SYNC,16_API_CONTRACT|Implement C10,C11,C16: local pending handover with photo/weight/location/time, SHA-256 and QR, Android PdfDocument, share and passport timeline. Clearly distinguish pending local hash check from server-confirmed record and protect PII.
T025|4|Implement approved second-phone QR confirmation|T002,T022,T023|05_DESIGN_STITCH,04_APPFLOW,16_API_CONTRACT|Implement R04,R05,V01 in responsive web; HTTPS camera scan plus reference-entry fallback, unknown-unsynced QR state, review/confirm measured terms, pending collector acknowledgement, public redacted verification and replay/conflict tests.
T026|4|Implement payment assertions and earnings projections|T023|06_SCHEMA,04_APPFLOW,16_API_CONTRACT|Record cash/UPI/other payment assertions with actor/time and acknowledgement/dispute; partial amounts and append-only reversals; derive gross/paid/pending totals without double counting; close only at confirmed receipt and acknowledged settled payment.
T027|4|Implement approved ledger and payment screens|T002,T024,T026|05_DESIGN_STITCH,04_APPFLOW|Implement C12,C13 and R05 payment/history portions; monthly/filter summaries, transaction detail, offline pending payment assertion, dues and disagreement; no implication that the app executes or bank-verifies money transfer.
T028|5|Implement data-quality and anomaly rules|T018,T019,T023,T026|03_TECHSPEC,18_DATA_PROVENANCE,MONITORING|Implement missing/invalid/duplicate/stale/inconsistent checks, price bounds, weight variance, image reuse and repeated events; record severity/reason/reviewer/resolution; no fraud accusation or destructive auto-correction.
T029|5|Implement admin maintenance and metrics APIs|T028|16_API_CONTRACT,06_SCHEMA,MONITORING|Implement admin directory review, material/alias/safety maintenance, price moderation, collector minimal view, event search, source/quality filters and aggregate metrics from persisted events; exclude demo data from real-impact totals.
T030|5|Implement approved admin/data-quality dashboard|T002,T029|05_DESIGN_STITCH,04_APPFLOW,18_DATA_PROVENANCE|Implement A01–A07: overview, collectors, facility verification, price/material/safety source editors, traceability search, quality queue and secondary-research evidence links. All counts/drill-downs come from APIs.
T031|5|Implement seven dataset exports and data lineage|T010,T011,T012,T023,T026,T029|18_DATA_PROVENANCE,16_API_CONTRACT,06_SCHEMA|Export all seven families as versioned CSV/JSON with provenance, safe redaction and manifests; produce handover PDF/CSV procurement logs labelled platform records; transaction outcomes feed reviewed price observations exactly once.
T032|5|Curate licensed public image dataset|T004,T005,T010|19_AI_ML,18_DATA_PROVENANCE|Select exact licensed datasets, save licence evidence and hashes, audit class relevance, deduplicate and group physical objects/source sequences into deterministic splits; document class gaps and no field-image claims.
T033|5|Train evaluate and export on-device model|T003,T032|19_AI_ML,20_TEST_ACCEPTANCE|Train Keras MobileNetV3-Small, record seeded configuration, validation threshold, untouched-test metrics/confusion matrix, quantized LiteRT export parity and model card. Record failure honestly; no invented accuracy or borrowed benchmark results.
T034|5|Integrate classifier into approved Android flow|T002,T017,T033|19_AI_ML,05_DESIGN_STITCH|Bundle model/labels/preprocessing/threshold/checksum, run off main thread, show real confidence and confirm/change/abstain; preserve suggestion and correction; test airplane mode, unsupported class, corrupt model and low-memory fallback.
T035|5|Create contextual safety content and review path|T004,T010|22_REGULATORY_SAFETY,14_TRANSLATION_AUDIO_AUDIT|Write short source-backed hi/mr/en material-specific safety cards and pictogram briefs for owner Stitch generation; version content, review hazards/routes and provide non-instructional battery/CRT warnings; no unlicensed image assets.
T036|5|Complete language resources and accessible interaction|T017,T020,T024,T027,T035|14_TRANSLATION_AUDIO_AUDIT,05_DESIGN_STITCH|Implement all collector hi/mr/en strings, material aliases, accessibility labels, plurals/currency/units and numeral preference; preserve chosen language offline/restart; no hardcoded English critical errors.
T037|5|Generate and wire offline Hindi/Marathi audio|T032,T035,T036|14_TRANSLATION_AUDIO_AUDIT,19_AI_ML|Use free licensed voice workflow for bundled prompts and number/unit grammar; inventory rights/text/checksum/duration; wire tap-to-hear dynamic ranges, rupees/paise, per-kg, pending/success/safety; verify no runtime cloud call. T032 supplies licence-review tooling, not image dependencies for audio content.
T038|5|Implement illustrative economics model|T004,T011,T026|23_UNIT_ECONOMICS,16_API_CONTRACT|Create transparent current/platform same-lot calculator and attributed assumptions; acquisition/transport/handling/rejections/time/payment-delay sensitivity, negative/zero baseline behavior and hypothetical downstream fee/cost sustainability; keep separate from realized earnings.
T039|5|Implement approved economics and safety views|T002,T030,T035,T037,T038|05_DESIGN_STITCH,23_UNIT_ECONOMICS,04_APPFLOW|Implement C17 safety hub/context cards and U01 interactive web economics, linked from admin/collector help where approved; clear illustrative labels and source drill-down; sliders/inputs update results; no preset claimed uplift.
T040|6|Verify security privacy and abuse boundaries|T025,T027,T030,T031|12_GUARDRAILS,11_SECRETS_CHECKLIST,20_TEST_ACCEPTANCE|Run owner/role/IDOR/replay/rate-limit/input/file-access tests; validate demo isolation, redacted QR/exports, no client secrets, token expiry/offline behavior, image EXIF removal, retention and backup controls; document residual limitations.
T041|6|Deploy hosted API database storage and web|T007,T008,T025,T030,T039,T040|DEPLOYMENT,11_SECRETS_CHECKLIST,25_RELEASE_CHECKLIST|Prepare reproducible Render/Supabase/Pages configuration, verify current free-plan terms and account settings, apply migrations, private storage/CORS/TLS, release API URL and health check; validate over cellular/outside LAN. Publishing requires the owner's existing or explicit deployment authorization.
T042|6|Prove local demo fallback and restore|T024,T027,T031,T040|DEPLOYMENT,13_RECOVERY,MONITORING|Run same contracts with Docker PostgreSQL/PostGIS and media volume, real-phone LAN debug networking, localhost/HTTPS QR fallback; backup and restore database+media+manifests; test without internet. Do not expose debug cleartext in release.
T043|6|Run cross-surface integration and fault acceptance|T015,T025,T027,T030,T031,T034,T037,T039,T040|20_TEST_ACCEPTANCE,17_OFFLINE_SYNC|Run deterministic domain tests, price/match/hash parity, offline crash/retry/media/conflict/auth/device-clock cases and complete collector→recycler→ledger→admin journeys. Store logs and case IDs, fix failures and rerun affected checks.
T044|6|Perform real-device and two-device usability tests|T041,T042,T043|20_TEST_ACCEPTANCE,24_DEMO_PRESENTATION|Owner uses real collector phone plus borrowed second Android browser; test camera/GPS/denial/restart/airplane mode/background/manual sync/QR, Hindi/Marathi and representative scenario usability. Identify tests as owner scenario tests, not collector fieldwork.
T045|6|Measure entry-level performance and artifact size|T034,T037,T043|03_TECHSPEC,19_AI_ML,20_TEST_ACCEPTANCE|Measure cold/cached launch, local save, compression, LiteRT latency, memory and APK including model/audio on named device; record p50/p95 and regressions, optimize lazy maps/assets without dropping required content.
T046|6|Audit all translations and audio on device|T036,T037,T039,T044|14_TRANSLATION_AUDIO_AUDIT,20_TEST_ACCEPTANCE|Check key parity, Devanagari rendering, large text/TalkBack, numeric/range pronunciation, all error/pending/review states and offline audio; native-speaker review where available remains explicitly unverified until performed.
T047|7|Freeze dataset and model evidence package|T031,T033,T044,T045,T046|18_DATA_PROVENANCE,19_AI_ML,21_RESEARCH_EVIDENCE|Produce release manifests, source/licence ledger, seven data cards, model card with actual results, data lifecycle demonstration, limitations and desk-research cards; distinguish facts/assumptions/demo rows and still-unmet primary fieldwork.
T048|7|Prepare PPT and presenter handoff|T044,T047|24_DEMO_PRESENTATION,21_RESEARCH_EVIDENCE,23_UNIT_ECONOMICS|Create final deck using verified implementation/screens and evidence; fill required organizer template, timing, five-presenter handoff, Q&A and honest limitations; remove stale statistics, EPR/credit/competitor overclaims.
T049|7|Record and validate demo video|T044,T045,T046,T048|24_DEMO_PRESENTATION,25_RELEASE_CHECKLIST|Record actual end-to-end demo with airplane mode, second-phone confirmation, two language audio, data quality and economics; publish/share link only with authorization; test link permissions outside owner account and retain local backup.
T050|7|Package release and submission handoff|T041,T042,T043,T044,T045,T046,T047,T048,T049|25_RELEASE_CHECKLIST,DEPLOYMENT,08_TRACKER|Produce installable signed APK, checksum/version/API URL, prototype web link, GitHub repository, PPT and video link; verify all RELEASE evidence and no missing tasks. Check official portal fields/cutoff and obtain final submission authorization if not already given; record actual submission result separately.
'''

# id | scope | title | task IDs | specification | historical source | observable acceptance
REQS = '''
R-GOV-01|RELEASE|Consistent SahiTol identity and latest scope|T001,T048|09_DECISIONS|P:2535-2569;P:2632-2658|Inspect app, package metadata, repository and deck: SahiTol is the product name, the SIH title is retained only as the problem title, and no superseded stack or selected feature is silently substituted.
R-GOV-02|RELEASE|Owner-generated Stitch frontend gate|T002,T017,T020,T022,T024,T025,T027,T030,T034,T039|05_DESIGN_STITCH|CURRENT_REQUEST|For each implemented screen/state find owner notification plus Stitch project/screen/revision and approval; a missing design leaves that UI waiting and never produces an invented replacement.
R-GOV-03|RELEASE|Traceable continuous agent execution|T001,T050|13_RECOVERY|CURRENT_REQUEST|In a fresh session invoke session-start then session-continue: agent reconstructs state, reads task specs, selects an eligible task, preserves blockers and updates status/evidence before progressing without routine next-task permission.
R-GOV-04|RELEASE|Deadline and all four deliverables|T048,T049,T050|25_RELEASE_CHECKLIST|P:2592-2615;P:2634-2647|Release handoff contains tested PPT, accessible demo video link, installable APK/prototype link and GitHub repo; portal cutoff/format and actual submission status are explicitly recorded.
R-ARC-01|RELEASE|Native Android architecture and feasibility|T001,T003|03_TECHSPEC|P:1970-1975;P:2602-2607|Approved feasibility screen on a named real Android phone captures photo, persists Room data through restart and performs offline LiteRT inference; Kotlin/Compose/Room/WorkManager remain the collector implementation.
R-ARC-02|RELEASE|Frozen API web database and storage stack|T001,T006,T008|03_TECHSPEC|P:2061-2286;P:2295-2316;P:2636-2646|Build and inspect API/web/database configuration: FastAPI, React/Vite, PostgreSQL/PostGIS, local volume and hosted private storage work through the documented contracts with dependency locks.
R-AUTH-01|RELEASE|Minimal profile and phone/PIN access|T007,T017|16_API_CONTRACT|E:5964-5979;P:1959-1973;P:2494-2495|Register/login with phone and PIN; store no plaintext PIN; profile uses ID/alias/language/general area, asks for no Aadhaar/PAN/bank details and shows recoverable auth errors.
R-AUTH-02|RELEASE|Role and object authorization|T007,T040|12_GUARDRAILS|E:2610-2638;E:6813-6857|Collector A cannot read/mutate B's lots; recycler A cannot confirm B's facility handover; collector cannot become admin by editing payload; invalid/expired tokens are rejected server-side.
R-AUTH-03|RELEASE|Offline session and safe logout|T007,T013,T015,T017|17_OFFLINE_SYNC|P:1611-1626;E:1285-1320|After successful activation disconnect and restart: local profile/drafts remain usable; expired token pauses authenticated sync; reauth resumes same operations; logout cannot silently discard pending data or expose it to another user.
R-AUTH-04|RELEASE|Isolated demo access without SMS|T007,T040,T050|12_GUARDRAILS|P:2005-2014;P:2646-2647|Bundled demo profile and demo OTP/bypass are explicitly labelled and isolated; public demo credentials cannot access non-demo users, verification controls or unrestricted admin actions.
R-LOT-01|RELEASE|Complete material taxonomy and aliases|T010,T017|18_DATA_PROVENANCE|E:509-537;E:2928-2959;E:6030-6049|Create draft lots for CRT,LCD,PCB,cable,battery,motor/magnet,mixed plastics,mixed electronics and UNKNOWN; hi/mr/en local aliases resolve to stable IDs, not hardcoded price values.
R-LOT-02|RELEASE|Camera image import compression and privacy|T008,T013,T017|06_SCHEMA|E:2664-2675;P:2305-2310|Take/import a photo, deny camera permission, retry capture and restart; saved image remains linked, upload validates type/size and strips EXIF; no-photo draft is allowed but evidence completeness is explicit.
R-LOT-03|RELEASE|Weight condition description and validation|T016,T017|04_APPFLOW|E:487-505;E:5981-6023|Save a draft then complete category/condition/description/positive finite weight; reject zero/negative/overflow values on submit; fractional kg round-trips as grams; suspicious large weight requires review without invented domain cap.
R-LOT-04|RELEASE|Collection and handover location/time provenance|T016,T024|06_SCHEMA|E:1003-1035;E:1854-1871|Record timestamps and GPS accuracy/capture age when permitted; denial uses labelled coarse/manual location or missing-data state; never fabricate coordinates or expose a home address in public records.
R-LOT-05|RELEASE|Durable draft lot lifecycle and cancellation|T013,T016,T017|04_APPFLOW|E:403-461;E:1792-1820|Create/edit/reopen/cancel a lot with stable UUID and legal transitions; restart preserves drafts; attempts to mutate confirmed historical terms or jump CLOSED→COLLECTED fail and are auditable.
R-PRICE-01|RELEASE|Price observations and in-app entry|T011,T020|18_DATA_PROVENANCE|E:627-648;P:2491-2492|Enter an observation with material/subcategory, region, date, unit, price kind and source; edit via revision, moderate and export it; unknown dates or unsupported conversions are quarantined.
R-PRICE-02|RELEASE|Indicative weighted range and lot valuation|T018,T020|03_TECHSPEC|E:652-676;E:2457-2488;E:6076-6105|A known comparable observation fixture yields specified weighted median/Q1/Q3 and estimate bounds in API and Android; weight changes recompute estimate; screen labels result indicative and retains snapshot/version.
R-PRICE-03|RELEASE|Source confidence freshness and empty prices|T018,T020|03_TECHSPEC|E:568-597;E:710-728|Recent/few/stale/no-data fixtures show correct count, sources, timestamp, confidence and reason; no-data is INSUFFICIENT, never zero or a hidden synthetic fallback.
R-PRICE-04|RELEASE|History trends and actual offer comparison|T018,T020,T021|03_TECHSPEC|E:5352-5361;E:3810-3822|View dated trend buckets and multiple offers in consistent units/regions; missing history displays a gap, no fabricated points; expired/noncomparable rates are labelled and do not become an agreed price.
R-PRICE-05|RELEASE|Quote anomaly review|T028,T030|03_TECHSPEC|E:682-706;E:6639-6658|Known low/high quotes trigger configured review reasons only when enough comparable data exists; alert says review, does not accuse fraud or block collector choice without a separate eligibility violation.
R-REC-01|RELEASE|Source-backed Delhi-NCR Maharashtra directory|T012|22_REGULATORY_SAFETY|P:2526-2541;P:2646-2647|Import CPCB plus DPCC and MPCB records with facility role/source document/page/date/registration and lineage; do not relabel a collection point as a recycler or claim that a list import creates a partnership.
R-REC-02|RELEASE|Verification levels and expiry|T012,T019,T029|22_REGULATORY_SAFETY|E:782-805;E:5816-5849|L0/L1/L2 never become verified formal destinations; stale/expired/revoked/unproven route authorization removes strong badge and matching eligibility even if original source was official.
R-REC-03|RELEASE|Facility materials rates pickup and service area|T012,T021,T022|06_SCHEMA|E:732-778;E:5936-5949|Facility user updates rates/availability/service area with provenance while authorization fields stay admin-controlled; unknown operational data stays unknown; acceptance/minimum-weight terms are visible.
R-REC-04|RELEASE|Route-aware eligibility|T019,T023|22_REGULATORY_SAFETY|E:249-280;E:830-859|Battery lot cannot match a facility evidenced only for e-waste; incompatible material, unverified current registration or unsupported service/weight constraints exclude before ranking and before confirmation.
R-REC-05|RELEASE|Explainable ranking with geography|T019,T020|03_TECHSPEC|E:2518-2540;P:2297-2301|Run fixed candidates: deterministic score and tie-break, PostGIS distance online, cached local parity within tolerance; expose contributions and unknowns; never invent pickup, price or reliability.
R-REC-06|RELEASE|Offline list online map and no-match path|T019,T020|05_DESIGN_STITCH|P:1995-2003;E:3792-3806|With network/maps/GPS unavailable directory list works with cached age and distance when possible; no-match can save/widen geography, never switch battery route; online MapLibre includes attribution and permitted tiles.
R-OFFER-01|RELEASE|Recycler inbound offer accept reject workflow|T021,T022|04_APPFLOW|E:3046-3055;E:5936-5949|Collector submits lot, linked recycler sees evidence and quotes/accepts/rejects; collector selects one live offer; rejected/expired requests preserve history and can return to another compatible match.
R-OFFER-02|RELEASE|Immutable agreed terms and offer races|T021,T023|04_APPFLOW|E:5485-5487;E:7600-7605|Two simultaneous acceptances leave one active agreement; cached expired offer cannot silently bind; later price-board refresh does not modify accepted terms; material/weight/price changes require explicit acknowledgement.
R-HAND-01|RELEASE|Offline pending handover evidence|T023,T024|17_OFFLINE_SYNC|P:2489-2490;E:5120-5169|In airplane mode create UUID proposal with photo references, grams, location quality, time, parties/terms and hash; restart shows PENDING_CONFIRMATION and sync pending, never recycler-confirmed.
R-HAND-02|RELEASE|Two-device recycler confirmation|T025,T044|04_APPFLOW|P:2612-2629;P:2641-2644|Borrowed second Android browser scans collector QR over HTTPS, identifies the correct facility/lot, submits authorized confirmation and collector sees it after pull; unsynced reference explains waiting and supports retry/manual reference.
R-HAND-03|RELEASE|Canonical hash and append-only event chain|T023,T024,T043|17_OFFLINE_SYNC|E:1081-1109;P:2139-2149|Same frozen JSON fixture hashes identically in Python/Kotlin/web; one altered byte invalidates expected digest; original proposal and confirmation events remain linked and unchanged; UI never describes bare SHA-256 as a signature.
R-HAND-04|RELEASE|Public verification and privacy|T023,T025,T040|16_API_CONTRACT|E:1039-1077;E:2642-2662|An unguessable receipt link shows current redacted status and record/hash comparison; public visitor cannot fetch phone/GPS/photos/payment details; QR possession alone cannot authorize confirmation.
R-HAND-05|RELEASE|Weight grade price disagreement|T023,T025,T027,T028|04_APPFLOW|E:3826-3898|Different measured weight/grade/price retains estimate and AI suggestion, sets pending acknowledgement/review and variance reason; neither party overwrites original facts; collector agreement or documented dispute is recorded.
R-HAND-06|RELEASE|Receipt PDF passport and procurement exports|T024,T025,T031|16_API_CONTRACT|E:970-1035;P:2305-2310|Export offline pending PDF and server confirmed PDF/CSV; identifiers/status/hash/provenance agree with timeline; record is called Digital Handover Record and includes non-EPR boundary, never an official manifest claim.
R-PAY-01|RELEASE|Cash optional UPI and payment recording|T026,T027|04_APPFLOW|E:1143-1167;E:6232-6249|Record cash without bank account/gateway; optional UPI/other records an assertion and reference, not transfer; both sides see actor/time/acknowledgement and can dispute.
R-PAY-02|RELEASE|Partial dues reversals and closure|T026,T027|06_SCHEMA|E:1113-1139;E:9548-9572|Two partial receipts sum once, duplicate operation does not increase paid total, overpayment is reviewed, reversal links original; RECEIVED with pending dues cannot become CLOSED; disagreement remains visible.
R-PAY-03|RELEASE|Collector earnings and transaction history|T026,T027|04_APPFLOW|E:1113-1139;E:6206-6230|Filter history/month and reconcile gross, acknowledged paid, asserted pending and remaining dues against transactions; offline view shows freshness; no demo earnings or estimates contaminate real settled totals.
R-OFF-01|RELEASE|Offline reference and local core journey|T009,T013,T017,T020|17_OFFLINE_SYNC|E:1285-1320;E:1586-1602|After bootstrap, airplane mode still allows material/safety/price/directory/history reads and photo/category/weight/lot/pending handover writes; fresh install offers clearly labelled demo reference or activation requirement, never an empty misleading success state.
R-OFF-02|RELEASE|Atomic durable outbox and image survival|T013,T043|17_OFFLINE_SYNC|E:1627-1655;P:2123-2137|Kill process during/after local save and media staging; either fully recover object+event+outbox+file or report unsaved failure; never drop a pending record through migration, cleanup or storage pressure.
R-OFF-03|RELEASE|Idempotency and partial batch acknowledgement|T014,T043|17_OFFLINE_SYNC|E:1659-1677;E:6320-6345|Resend an operation after server commit/ACK loss and in mixed-success batches; each accepted effect occurs once, different payload with reused ID conflicts, successful siblings stay acknowledged.
R-OFF-04|RELEASE|Versioned conflicts and dependency order|T014,T015,T043|17_OFFLINE_SYNC|E:1683-1717;E:9031-9053|Out-of-order lot/media/handover operations wait on parents; concurrent changes return current server version without erasing local proposal; reference tombstones update caches while historical receipts retain snapshots.
R-OFF-05|RELEASE|WorkManager retries foreground sync and auth pause|T015,T017,T043|17_OFFLINE_SYNC|P:1472-1483;P:2123-2137|With intermittent network/reboot/background restriction sync resumes durably or via manual button; 401 pauses for auth, 409 review, 422 repair, 429 backoff and 5xx retry without busy loop or lost records.
R-OFF-06|RELEASE|Visible queue and recoverable failure states|T015,T017,T043|05_DESIGN_STITCH|E:7607-7609|Collector can distinguish local/sending/synced/needs-login/conflict/rejected, inspect queue count/last sync, retry safely and retain a support reference; no generic green success on HTTP failure.
R-ML-01|RELEASE|Licensed suitable public dataset only|T032,T047|19_AI_ML|P:2628-2629;E:1987-2008|Every training image has permitted-use evidence, source/license/hash/class/object-group/split; no fabricated field images; class coverage report exposes generic datasets that do not cover actual e-waste taxonomy.
R-ML-02|RELEASE|Reproducible leakage-free training and evaluation|T033,T047|19_AI_ML|E:2398-2449;E:6676-6710|Train from saved configuration with object-group splits and training-only augmentation; report actual untouched-test macro/per-class F1, confusion matrix, counts/limits, calibration threshold and quantization parity.
R-ML-03|RELEASE|Bundled offline advisory classifier|T034,T044|19_AI_ML|P:2639-2642;E:2351-2394|Real SahiTol model predicts offline on phone with versioned preprocessing; user confirms/changes; low-confidence/OOD/corrupt-model fallback stays usable; no automatic certification, pricing or route determination.
R-ML-04|RELEASE|Correction data and measured model constraints|T034,T045,T047|19_AI_ML|E:2402-2419;E:3328-3342|Persist suggestion/confidence/model version separately from human label; report correction/abstention denominators and inference/APK/memory on actual device; no training reuse without documented rights/purpose.
R-SAFE-01|RELEASE|Contextual pictorial safety guidance|T035,T039|22_REGULATORY_SAFETY|E:1171-1197;E:6251-6267|PCB/cable/CRT/battery selection opens appropriate short pictorial warning in both languages offline; content is sourced/versioned and avoids instructions for unsafe processing.
R-LANG-01|RELEASE|Complete Hindi Marathi and English fallback|T036,T046|14_TRANSLATION_AUDIO_AUDIT|E:1201-1231;P:2636-2643|All collector critical keys, labels, validation/denial/conflict/payment states and dynamic material terms work in hi/mr; language persists; unavailable translation is reported in audit, not hidden by English fallback.
R-LANG-02|RELEASE|Offline audio prompts and spoken prices|T037,T046|14_TRANSLATION_AUDIO_AUDIT|P:1949-1950;P:2618-2621;E:5356-5361|In airplane mode tap Hindi and Marathi audio for changing price ranges, decimals, rupees/paise/per-kg and safety/pending/success; spoken value exactly matches visible value; asset licences and missing-clip behavior are recorded.
R-UX-01|RELEASE|Low-literacy accessible approved interactions|T017,T036,T044,T046|05_DESIGN_STITCH|E:3057-3117;E:5519-5527|Core screens use approved icons/photos, short labels and tap-to-hear, primary 56dp mobile targets, no color-only status, at most three primary inputs per step; large text/TalkBack/numeric input and explicit numeral preference remain usable.
R-UX-02|RELEASE|Entry-level Android performance|T045|03_TECHSPEC|E:3121-3135;E:7279-7300;P:2309-2310|Record named device, APK/model/audio sizes, memory and launch/save/compression/API/model timings against documented budgets; any miss stays visible with remediation, no borrowed benchmarks.
R-DATA-01|RELEASE|Material dataset reference and observations|T010,T016,T031,T047|18_DATA_PROVENANCE|E:1970-1983;E:5351-5365|Export material observations with category/subcategory/description/image/weight/condition/source/value linked to lots while catalog remains distinct; new lot produces an observation through normal workflow.
R-DATA-02|RELEASE|Price dataset lifecycle and feedback|T011,T018,T031,T047|18_DATA_PROVENANCE|E:1905-1922;E:5491-5498|Import→validate→review→aggregate→display→confirmed-transaction feedback→history/export works; one eligible transaction adds one sourced price observation; disputes/demo records do not contaminate real summaries.
R-DATA-03|RELEASE|Recycler dataset lifecycle|T012,T021,T029,T031,T047|18_DATA_PROVENANCE|E:1926-1945;E:6533-6541|Import facility, review source/current status, update operational data, refresh/expire verification and export versions; original registry claim and later operational update remain separately attributable.
R-DATA-04|RELEASE|Transaction dataset generated by workflow|T026,T031,T047|18_DATA_PROVENANCE|E:1949-1967|A demonstrated lot→offer→handover→payment produces a transaction export with party IDs, original/final weights/values, locations/times and separate payment/lifecycle status without hand-inserting completion rows.
R-DATA-05|RELEASE|Traceability dataset generated by events|T023,T031,T047|18_DATA_PROVENANCE|E:1854-1884|Export collection through confirmed receipt/status events with evidence refs, weights, times, location quality, reference and confirmation; verify chain and correction lineage without mutable-history loss.
R-DATA-06|RELEASE|Minimal collector dataset and anonymization|T007,T031,T040,T047|18_DATA_PROVENANCE|E:1888-1901|Export collector ID/language/general area/history/totals with PII redacted by purpose; onboarding and transactions generate it; public export excludes phone, exact home location and credentials.
R-DATA-07|RELEASE|AI training dataset card and tabular links|T032,T033,T047|19_AI_ML|E:1987-2008;E:6527-6541|Deliver training manifest/card with source, quality, size, labels, object splits and licensing plus nullable weight/price/location/transaction links where actually observed; absent measurements remain null, never inferred truth.
R-DATA-08|RELEASE|Provenance and demo isolation everywhere|T005,T029,T031,T040|18_DATA_PROVENANCE|P:2646-2647;E:2678-2705|Display and export origin_class/source_kind/is_demo/date/version; public commercial data is not OFFICIAL; app-generated demo data is not real trade; mixed datasets disclose breakdown and synthetic lineage propagates.
R-DATA-09|RELEASE|Import cleaning geocoding and validation tools|T005,T012,T031|18_DATA_PROVENANCE|P:2312-2313;E:4022-4048|Rerun imports deterministically with checksums, preserve original documents and extraction locators, quarantine malformed rows, cache permitted geocodes and report accuracy; never silently discard or invent values.
R-DATA-10|RELEASE|Synthetic generator and edge-case scenarios|T005,T043|18_DATA_PROVENANCE|E:2219-2272|Seeded generator produces labelled valid workflow fixtures and separate invalid/retry/duplicate/mismatch/stale/reject/cancel scenarios; re-running does not duplicate seed identities or label generated records official.
R-DATA-11|RELEASE|Seven data cards and versioned exports|T031,T047|18_DATA_PROVENANCE|E:3944-4018;E:5365-5367|For all seven families deliver schema/version/count/source/license/validation/update/use/limitations and export checksum; counts reconcile with stored rows and demo filters; no completed card contains invented values.
R-ADMIN-01|RELEASE|Admin CRUD source and verification workflow|T029,T030|16_API_CONTRACT|E:3057-3065;E:5951-5960|Admin can review facilities, materials/aliases/safety, prices and source revisions; ordinary recycler cannot approve itself; edits are audited and sync to caches without rewriting old receipts.
R-ADMIN-02|RELEASE|Data quality review dashboard|T028,T030|MONITORING|E:3570-3594;E:4022-4066;P:2644-2645|Dashboard calculates missing/invalid/stale/duplicate/inconsistent/source coverage and demo fractions; drill into a flag and resolve with actor/reason; all percentages have denominators and real query evidence.
R-ADMIN-03|RELEASE|Analytics and correct impact metrics|T029,T030|MONITORING|E:3260-3342;E:5628-5636|Metrics derive from events with time/region/provenance filters: activity/quotes/matches/dues/disputes/sync/model quality and verified received grams; exclude demo and never equate received material with proven recycling or CO2 savings.
R-ECON-01|RELEASE|Illustrative unit-economics screen|T038,T039|23_UNIT_ECONOMICS|P:2614-2619;P:2645-2646;E:3183-3218|Change source-linked same-lot input assumptions and observe recalculated current/platform net, delta and valid percentage; show negative/no-benefit cases and explicit illustrative label separate from actual ledger.
R-ECON-02|RELEASE|Platform sustainability without collector fees|T038,T048|23_UNIT_ECONOMICS|E:3222-3257;E:9597-9603|Show hypothetical downstream fee revenue minus variable/fixed operating costs and break-even sensitivity; no fee actually charged, credit eligibility or guaranteed uplift implied.
R-RES-01|RELEASE|Honest secondary research and personas|T004,T047,T048|21_RESEARCH_EVIDENCE|P:2517-2521;P:2646-2647|Research package identifies each published source, its scope and design inference; personas/scenarios are labelled simulated; deck says no primary interviews completed and never invents participants or quotes.
R-RES-02|EXTERNAL_GAP|Two working collector/aggregator field research|T004,T047,T048,T050|21_RESEARCH_EVIDENCE|E:5367-5369;P:2538-2540;P:2647-2647|This remains UNMET while desk research is the owner choice. Only actual consented engagement with at least two working participants and evidence could satisfy it; documentation or synthetic scenarios cannot mark it passed.
R-REG-01|RELEASE|Receipt terminology and no false authorization|T023,T024,T031,T048|22_REGULATORY_SAFETY|E:186-245;E:6176-6204;P:2651-2653|App/PDF/CSV/deck call the artifact a platform Digital Handover Record; collector identity is not a licence; no official EPR certificate, government endorsement or established CPCB integration is claimed.
R-SEC-01|RELEASE|PIN abuse secrets and transport safety|T007,T040,T041|12_GUARDRAILS|E:2610-2638;P:2301-2301|Rate-limit PIN attempts, restrict role grants, rotate/revoke sessions, verify release HTTPS and restrictive CORS; APK/web/repo/log/QR contain no server key, PIN or private database credentials.
R-SEC-02|RELEASE|Privacy media access retention and audit|T008,T040,T042|12_GUARDRAILS|E:2642-2675;E:6833-6857|Private images require authorization; signed URLs expire; uploads cannot traverse filesystem; exports redact PII; retention/deletion policy preserves justified audit and pending data while clearing obsolete access safely.
R-OPS-01|RELEASE|Hosted remote judge access|T041,T044,T050|DEPLOYMENT|P:2610-2611;P:2638-2638|Install release APK and open web console outside developer Wi-Fi; HTTPS API, PostGIS, private storage and QR work; cold start has recoverable UI; persistent photos survive API redeploy.
R-OPS-02|RELEASE|Reproducible local fallback and recovery|T042|DEPLOYMENT|P:2478-2479;P:2301-2301|Fresh local Compose environment runs same schema and fixture journey; Android debug LAN configuration works; database/media restore rehearsed; browser scan fallback handles insecure local camera context without weakening release TLS.
R-OPS-03|RELEASE|No required paid runtime dependency|T001,T037,T041|11_SECRETS_CHECKLIST|P:1764-1806;E:1519-1537|Audit dependency/service/config list and execute core with cloud speech/maps/AI unavailable; no mandatory SMS, LLM, payment gateway, custom domain or billing upgrade is required; current free-plan/account limitations documented.
R-OPS-04|RELEASE|Monitoring and diagnostics|T028,T029,T042|MONITORING|E:3282-3342;E:7607-7609|Health and redacted structured logs expose failed sync/conflicts/media/DB errors with correlation IDs; dashboard denominators and last refresh distinguish outage from empty data; actionable local recovery steps work.
R-QA-01|RELEASE|Critical end-to-end and adversarial acceptance|T043,T044|20_TEST_ACCEPTANCE|E:7217-7277;P:733-788|Pass online and airplane-mode lot→price→match→pending QR→sync→second-phone confirmation→payment→ledger→admin plus duplicate/crash/denial/stale/conflict/auth tests with actual logs and device evidence.
R-QA-02|RELEASE|Live scenario demonstration and backup|T044,T049|24_DEMO_PRESENTATION|E:5367-5369;E:7176-7213|A person actually performs the complete journey on devices, records failures and fixes, and produces playable demo/backups; no unexecuted script or prefilled database is represented as live usability evidence.
R-DOC-01|RELEASE|Outsider documentation and presenter readiness|T047,T048,T050|00_README|CURRENT_REQUEST;P:2585-2605|New reader follows README to scope/architecture/decisions/data/run/demo; presenters can explain sources, offline pending vs confirmed, price limits, model limits, battery route and unmet fieldwork without relying on chat history.
'''

def rows(raw):
    return [x.strip().split('|') for x in raw.strip().splitlines() if x.strip()]

tasks = []
for id, phase, title, deps, reading, output in rows(TASKS):
    tasks.append(dict(id=id,phase=int(phase),title=title,dependencies=deps.split(',') if deps else [],reading=[f'docs/{x}.md' for x in reading.split(',')],output=output))

requirements = []
tests = []
for n,(id,scope,title,ts,spec,source,acceptance) in enumerate(rows(REQS),1):
    test = f'AT-{n:03}'
    requirements.append(dict(id=id,scope=scope,title=title,tasks=ts.split(','),spec=f'docs/{spec}.md',source=source.split(';'),test=test,acceptance=acceptance))
    tests.append(dict(id=test,requirement=id,acceptance=acceptance,kind='external obligation' if scope=='EXTERNAL_GAP' else 'acceptance'))

catalog = dict(version=1,date='2026-09-28',tasks=tasks,requirements=requirements,tests=tests)
status = dict(tasks={t['id']:dict(status='TODO',evidence=[],note='Not implemented.',owner='Owner + coding agent') for t in tasks},tests={t['id']:dict(status='UNMET' if t['kind']=='external obligation' else 'NOT_RUN',evidence=[],note='Primary fieldwork not conducted; owner chose secondary research.' if t['kind']=='external obligation' else '') for t in tests})
P.mkdir(parents=True,exist_ok=True)
for name,data in [('catalog.json',catalog),('status.json',status)]:
    (P/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Created {len(tasks)} tasks, {len(requirements)} requirements, {len(tests)} acceptance cases.')
